plugins { id 'com.android.application' }

android {
    namespace 'pl.mp.kodiautostart'
    compileSdk 35
    defaultConfig {
        applicationId 'pl.mp.kodiautostart'
        minSdk 24
        targetSdk 28
        versionCode 3
        versionName '3.0'
    }
    buildTypes {
        release { minifyEnabled false }
    }
}
